apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
spec:
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80


